
dna = "TGAATGACTCTGTCTACCTCAGAATGACTTTTGGGCACCTTTACGAGGTGTTTCATGCTA" \
      "ACCCTGGTACTGTGACTGGCTCAGCAGTAGGTTGCAACCCAGACGTGTTTTGGAGTAAAC" \
      "TACCGATTCTGCTGCCTGGGTCACTCTTTGCCTTTGACTACTCAGGATATGATGCTAGTC" \
      "TCAGCCCGGTATGGTTCAGGGCTCTAGAAGTTGTGTTACGGGAGATTGGGTATTCAGAGG" \
      "AGGCCGTGTCCCTAATAGAAGGAATCAACCACACCCACCATGTGTACCGGAACAAGACAT" \
      "ACTGTGTACTTGGTGGGATGCCCTCAGGGTGCTCTGGTACTTCCATCTTCAATTCAATGA" \
      "TCAATAACATCATCATTAGAACCCTTTTGATCAAAACCTTTAAGGGAATAGACCTGGATG" \
      "AGTTGAACATGGTGGCCTATGGGGACGATGTGCTGGCCAGTTACCCTTTTCCTATTGATT" \
      "GCCTTGAATTGGCTAAGACTGGCAAAGAGTATGGTTTGACCATGACTCCTGCAGACAAAT" \
      "CACCCTGTTTCAATGAAGTAACATGGGAAAATGCTACCTTCCTGAAGAGAGGGTTCTTGC" \
      "CAGACCACCAATTTCCATTCTGGTACCCACCCTACGATGCCCATGAGAGAGATCCATGAGT" \
      "CCATTCGATGGACTAAGGACGCGCGTAACACCCAGGATCACGTGCGCTCCCTGTGTCTAT" \
      "TGGCATGGCACAATGGTAAGGATGAATATGAAAAGTTTGTGAGTGCAATTAGATCAGTTC" \
      "CAGTTGGAAAAGCGTTGGCCATTCCTAACTTTGAGAATCTGAGAAGAAATTGGCTCGAAT" \
      "TGTTTTAATATTACAGTTTAAAGCTGAACCCCACTAGAAATCTGGTCGTGTTAATGACTA" \
      "GTGGGGGTAAATTTGTTATAACCGGAATAGC"

restriction_dict = {'KpnI': 'GGTACC',
                    'EcoRI': 'GAATTC',
                    'HindIII': 'AAGCTT',
                    'TaqI': 'TCGA',
                    'AciI': 'CCGC',
                    'NotI': 'GCGGCCGC',
                    'HaeIII': 'GGCC',
                    'EcoRV': 'GATATC'}

for key, value in restriction_dict.items():
    cnt = dna.count(value)
    print(key + ", " + value + "found " + str(cnt) + " times")